2024/06/19 06:29:08 [error] 22#22: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2024/06/19 06:29:08 [error] 22#22: *1 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/06/19 06:32:13 [error] 22#22: *12 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2024/06/19 13:54:10 [error] 22#22: *2 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2024/06/19 13:54:10 [error] 22#22: *2 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/06/19 13:54:18 [error] 22#22: *2 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2024/06/19 13:54:20 [error] 22#22: *2 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2024/06/20 10:55:02 [error] 22#22: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2024/06/20 10:55:03 [error] 22#22: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2024/06/25 12:21:39 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "OPTIONS /api/auth/login HTTP/1.1", upstream: "http://172.19.0.4:3001/api/auth/login", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:21:50 [error] 29#29: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "OPTIONS /api/auth/login HTTP/1.1", upstream: "http://172.19.0.4:3001/api/auth/login", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:22:54 [error] 29#29: *3 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "OPTIONS /api/auth/login HTTP/1.1", upstream: "http://172.19.0.4:3001/api/auth/login", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:58:45 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:58:46 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:58:46 [error] 29#29: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:58:46 [error] 29#29: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:58:46 [error] 29#29: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 12:58:46 [error] 29#29: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:52 [error] 29#29: *34 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:55 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:55 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:55 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:55 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:55 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:55 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 13:01:55 [error] 29#29: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "OPTIONS /api/auth/invite HTTP/1.1", upstream: "http://172.21.0.2:3001/api/auth/invite", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 15:00:52 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/auth/login HTTP/1.1", upstream: "http://172.18.0.4:3001/api/auth/login", host: "localhost", referrer: "http://localhost:3000/"
2024/06/25 15:01:01 [error] 29#29: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "OPTIONS /api/auth/login HTTP/1.1", upstream: "http://172.18.0.4:3001/api/auth/login", host: "localhost", referrer: "http://localhost:3000/"
2024/06/28 07:44:40 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "OPTIONS /api/auth/login HTTP/1.1", upstream: "http://172.19.0.3:3001/api/auth/login", host: "localhost", referrer: "http://localhost:3000/"
